### ISSUE TITLE
[BUG] Lobby shows "1 of 2 players ready"

### ISSUE THREAD

**Issue by Sebastian-Belkner** [EnderdracheLP/MultiplayerCore.Quest#14] opened 2022-10-23 21:08 UTC
**Describe the bug**
At least one players appears to be not ready after everyone presses the ready button

**To Reproduce**
1. Start your Beat Saber  and go to "Modded Online"
2. Select the same server of the person you'd like to play with
3. Find yourself in a lobby with that person
4. Choose a song, press ready.
5. Then, wait for the countdown to finish.
6. After countdown, it says "1 of 2 players ready".
7. We also tried with non-custom song.. same problem

**Expected behavior**
Playing together :p

**Screenshots**
Can do if really needed, but don't think it is?

**Quest (please complete the following information):**
 - Device: Quest 2
 - Game Version: [e.g. 1.25.1]
 - Mod Version: [e.g. 1.3.1]

**Additional context**
We really appreciate your efforts! Thanks a lot for this mod, you are a hero

We filled out google forms, but you only request crashes there, so we thought might as well open an issue here
<3

**Comment by michael-r-elp** [comment] 2022-10-24 16:46
Interesting, normally if it gets stuck like that it would mean that the other players download got stuck, but since you said it also happened with base game songs, I'm quite confused about the cause here.

It would help if I could get the other players game logs and possibly a description on what they saw, if they saw the same 1 of 2 players ready or something different.

Another possible cause could be a server side issue.

**Comment by Sebastian-Belkner** [comment] 2022-10-24 19:05
We are only using base game songs for now.

We did a few combinations to see what happens,

1. Either of us creating the server,
2. Choosing the same map, or different maps, or one doesn't choose a map at all
All lead to the same issue.

If either of us (host or other player) leaves the room while '1 of 2 players ready', the player still in the server room gets his screen turned black, the player sees the info 'waiting for other player' and than the song starts.


Now, what we observed.

- If Host presses ready, the countdown starts even when the other player has not pressed ready.
- At the end of the countdown the info '1 of 2 players ready' appears, as before.
- Now, 'not-ready'-player presses ready button -> info: '1 of 2 [...]' remains
- but the arrow in the partylist indicates that the player is now ready


Any idea how we can help you to fix it?

**Comment by michael-r-elp** [comment] 2022-10-24 19:20
The info saying who's ready at the end actually indicates the amount of players that have the map downloaded, not the ones that pressed ready, likewise the host pressing start will initiate the countdown, the other players pressing ready will just reduce the time on the countdown

To help me out on what's going on, can you reproduce the issue and then open sidequest and get the global log file from both you and the other player for me that could help
You'll find it within the files on quest under /sdcard/Android/data/com.beatgames.beatsaber/files/logs/GlobalLog_3_14_0.log

That might help me see what is happening there

Also do you get that issue with all custom maps, or just some?

**Comment by cubicgraphics** [comment] 2022-10-24 19:47
Are you able to play anything when there is only one player in the mp lobby?

**Comment by Sebastian-Belkner** [comment] 2022-10-24 20:02
Yes, we can both start a song with only ourselves in the lobby

**Comment by Sebastian-Belkner** [comment] 2022-10-24 20:19
We just reproduced the isee again and give you the full files
[GlobalLog_3_14_01.log](https://github.com/EnderdracheLP/MultiplayerCore.Quest/files/9855065/GlobalLog_3_14_01.log)
[GlobalLog_3_14_0.log](https://github.com/EnderdracheLP/MultiplayerCore.Quest/files/9855071/GlobalLog_3_14_0.log)

_0.log was host

**Comment by michael-r-elp** [comment] 2022-10-24 20:24
I might have found a possible cause, I'll just need a few minutes to confirm it

**Comment by michael-r-elp** [comment] 2022-10-24 20:38
[MultiplayerCore1.3.2-Dev.1 (Please Unzip QMOD Inside).zip](https://github.com/EnderdracheLP/MultiplayerCore.Quest/files/9855205/MultiplayerCore1.3.2-Dev.1.Please.Unzip.QMOD.Inside.zip)

Can you and the other player give this build a try, had to zip the qmod since github doesn't allow uploading .qmod files directly

**Comment by Sebastian-Belkner** [comment] 2022-10-24 21:00
Well done Michael! Nice!
We have checked for a non-custom map real quick and it works now.

(note: Host can now start song without confirming ready-check from players)

**Comment by michael-r-elp** [comment] 2022-10-24 21:05
Great, everything works as intended then

I'll close the issue once I released the fixed version

If you see that issue again in some way let me know

**Comment by michael-r-elp** [comment] 2022-10-29 19:20
Got some time today, fix is released, I'll close this issue now

**Closed by michael-r-elp** 2022-10-29 19:20 UTC
Labels: bug
