### ISSUE TITLE
[Bug]: Beat Saber keeps stopping

### ISSUE THREAD

**Issue by 0xGuigui** [EnderdracheLP/MultiplayerCore.Quest#17] opened 2022-11-04 12:24 UTC
### Describe the bug

Combined with Beat Together 1.6.0, as soon as I try to start Beat Saber, the game just crashes. Works when I disable MultiplayerCore, or when I reinstall it every time I restart the game. No idea what the bug could be

### Steps to reproduce

Install MultiplayerCore 1.3.2 with BMBF for Beat Saber 1.25.1
Activate it and sync it
Start Beat Saber for the first time, it works
When you quit the game and try to restart it, it doesn't work anymore.

### Actual Behavior

On the second and next start of the game, impossible to start Beat Saber with this mod activated. I tried to empty the cache of Beat Saber, and reinstall the game. Nothing works....

### Device

Quest 2

### Game Version

1.25.1

### Mod Version

1.3.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michael-r-elp** [comment] 2022-11-04 12:30
It's a known issue, that's being looked into, I've been planning on potentially testing if disabling a specific feature in MpCore would stop the crash on startup
There's also an ongoing rewrite of MpCore that in the future could also potentially fix the issue, see #16 

I might get back to you sometime soon, to try out a test build with the suspected feature disabled to see if that manages to fix your issue.

**Comment by michael-r-elp** [comment] 2022-11-05 12:43
Can you give this qmod a try and tell me if you still crash on startup, crash at some other point or if it works this time?
If you still crash on startup I'll have to try something else
[MultiplayerCore1.3.3-Dev.1.qmod.zip](https://github.com/EnderdracheLP/MultiplayerCore.Quest/files/9943813/MultiplayerCore1.3.3-Dev.1.qmod.zip)

**Comment by Nysioko** [comment] 2022-11-05 23:07
Hello, I tried to reproduce the bug with your dev version, it seems to work, without being indiscreet, what did you change? :o

**Comment by michael-r-elp** [comment] 2022-11-05 23:40
> Hello, I tried to reproduce the bug with your dev version, it seems to work, without being indiscreet, what did you change? :o

I removed the Downloaded Songs Gameplay Setup Menu that you could open on the left side from the mod, since that was the only thing remaining that could cause a crash on game start, sine I have everything else initialize much later.
This unfortunately means I'll have to figure out a better solution for implementing the UI portion of the mod

**Comment by raineio** [comment] 2022-11-06 00:07
@Nysioko the reason the issue might persist between restarts is memory could be persistent. It's not the first time I've heard about certain issues pertaining to mods persisting after a game restart and likely won't be the last, but as Ender said, I am currently working on a rewrite to hopefully alleviate some issues (and to bring it more in line with PC MpCore in the process).

My theory might be wrong, and anyone more knowledgeable about memory are free to correct me ^^

**Comment by sc2ad** [comment] 2022-11-06 03:38
This is not true-- memory is allocated virtually and is not persistent between application relaunches. A soft restart, on the other hand, can cause residency to take place. That said, UI causing bugs is not an incredibly outlandish claim and I'm glad you were able to track it down! That gives me a lot of hope for closing on this issue more and more as we continue to make forward progress.

**Comment by wmyfelix** [comment] 2022-12-27 11:25
1.26.2 crash when clicking online mode button on the menu.

**Comment by Kevman95** [comment] 2022-12-31 15:09
@wmyfelix Try the latest 1.27 version and see if you can reproduce.

**Comment by wmyfelix** [comment] 2023-01-02 08:17
> @wmyfelix Try the latest 1.27 version and see if you can reproduce.

Fixed. Though I've never enter the mode successfully (CFR-9)

**Comment by michael-r-elp** [comment] 2023-01-02 08:29
I'm glad it's no longer crashing, though I really wonder what's up with the CFR-9 error some people get.

Are you using the latest for 1.27 version 1.3.6?
There was some bug in the 1.3.5 release that was related to checking the status

**Comment by wmyfelix** [comment] 2023-01-02 08:56
@michael-r-elp I've tried 1.3.6, 1.3.4, 1.3.3 with the BeatSaber and BeatTogether versions it corresponded to, they all occurred CFR-9 or CFR-3, particularly when CFR-9 happened, it can at least show a error of the room is full when I was joining on intended, but when CFR-3 happened, it just show the error no matter the room I was attempting to join in is full or not. Since I'm in Mainland China, these may related to my VPN, the two errors are occurred separately corresponded to the VPN I was using for connection.

**Comment by wmyfelix** [comment] 2023-01-02 08:59
By the way, the situation above can also be applied without MultiplayerCore.Quest.

**Comment by michael-r-elp** [comment] 2023-01-02 15:25
@wmyfelix Does connecting to BT servers within China maybe work?
You'd have to create a file like this one https://github.com/BeatTogether/BeatTogether.Quest/blob/master/BeatTogether.cfg with the following content (this is just a random chinese BT server I picked)
`File: BeatTogether.cfg`
```cfg
bs.xiu137.xyz
2328
http://bs.xiu137.xyz:23280/status
```
Then upload that to `sdcard/ModData/com.beatgames.beatsaber/Configs/BeatTogether.cfg` at least I believe it was something along the lines (I can't look it up right now), it should be the config folder within `sdcard/ModData/com.beatgames.beatsaber/`

The Modded Online Button in-game should then show the hostname of the server instead, then see if connecting to that works
It might be some weird thing with your VPN maybe that could block UDP port 2328 or something

**Comment by wmyfelix** [comment] 2023-01-02 18:41
@michael-r-elp It still shows CFR-9 even if I route the specific UDP connection not passing to the VPN tunnel, but it was fixed after letting the DNS return the real IP rather than the fake IP return by [Clash](https://github.com/Dreamacro/clash).

**Comment by michael-r-elp** [comment] 2023-01-02 18:46
Ok, so I assume it was an issue with Clash on your end then

**Comment by wmyfelix** [comment] 2023-01-02 20:57
> 

Yeah, thanks for your great help!

**Closed** 2024-11-11 18:53 UTC
Labels: bug
